# Generated by Django 5.0.3 on 2024-06-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='availability',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
