# Generated by Django 5.0.3 on 2024-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_remove_accommodation_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel')], default='Hotel', max_length=10),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='room_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
