# Generated by Django 5.0.3 on 2024-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodation_accommodation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='room_details',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='apartment_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.CharField(default='București', max_length=100),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='country',
            field=models.CharField(default='Romania', max_length=100),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON')], default='RON', max_length=3),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='hotel_apartments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='hotel_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='star_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel')], max_length=10),
        ),
    ]
