# Generated by Django 5.0.3 on 2024-06-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_remove_accommodation_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='price',
        ),
    ]
