# Generated by Django 5.0.3 on 2024-06-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_remove_accommodation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='apartment_rooms',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='hotel_apartments',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='hotel_rooms',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Hotel', 'Hotel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON')], max_length=3)),
                ('availability_start', models.DateField()),
                ('availability_end', models.DateField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='apartment_images/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='accommodation.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('economic', 'Economic'), ('standard', 'Standard'), ('superior', 'Superior')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON')], max_length=3)),
                ('availability_start', models.DateField()),
                ('availability_end', models.DateField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodation.accommodation')),
            ],
        ),
    ]
