# Generated by Django 5.0.3 on 2024-06-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_remove_accommodation_apartment_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='accommodation_type',
        ),
    ]
