# Generated by Django 5.0.3 on 2024-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_alter_accommodation_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
