# Generated by Django 5.0.3 on 2024-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_alter_accommodation_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='breakfast_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='outdoor_activities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='reception_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
