# Generated by Django 5.0.3 on 2024-06-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0010_accommodation_accessible_accommodation_bar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='accessible',
            new_name='accessibility',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='breakfast_included',
            new_name='breakfast',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='gym',
            new_name='fitness_center',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='pets_allowed',
            new_name='pets',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='reception_24_7',
            new_name='reception',
        ),
    ]
