# Generated by Django 5.0.3 on 2024-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='number_of_apartments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
