# Generated by Django 5.0.3 on 2024-06-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0019_apartmentimage_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
    ]
