# Generated by Django 5.0.3 on 2024-06-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0020_remove_apartment_images_remove_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_apartments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
